# Generated by Django 2.0.2 on 2018-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='professor_subjects', to='reviews.Course'),
        ),
    ]
